// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt8BNhbNEpWN_zMQDGAiMvDtlDwHwkNe0',
    appId: '1:465763290306:web:cf1cced899c9f482207f5b',
    messagingSenderId: '465763290306',
    projectId: 'week12-7b4d5',
    authDomain: 'week12-7b4d5.firebaseapp.com',
    storageBucket: 'week12-7b4d5.firebasestorage.app',
    measurementId: 'G-E5CCJSWK7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvhF4-KIVEc1qgw-GXT0SCFlOw7PpwZWE',
    appId: '1:465763290306:android:757789cb7c91e35e207f5b',
    messagingSenderId: '465763290306',
    projectId: 'week12-7b4d5',
    storageBucket: 'week12-7b4d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMTIx2Em4JIbJ6YzOtDRGB0JRbuin-ZtQ',
    appId: '1:465763290306:ios:11cc1d1e2bdbb025207f5b',
    messagingSenderId: '465763290306',
    projectId: 'week12-7b4d5',
    storageBucket: 'week12-7b4d5.firebasestorage.app',
    iosBundleId: 'com.example.week12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMTIx2Em4JIbJ6YzOtDRGB0JRbuin-ZtQ',
    appId: '1:465763290306:ios:11cc1d1e2bdbb025207f5b',
    messagingSenderId: '465763290306',
    projectId: 'week12-7b4d5',
    storageBucket: 'week12-7b4d5.firebasestorage.app',
    iosBundleId: 'com.example.week12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt8BNhbNEpWN_zMQDGAiMvDtlDwHwkNe0',
    appId: '1:465763290306:web:9c0379ea7fe15656207f5b',
    messagingSenderId: '465763290306',
    projectId: 'week12-7b4d5',
    authDomain: 'week12-7b4d5.firebaseapp.com',
    storageBucket: 'week12-7b4d5.firebasestorage.app',
    measurementId: 'G-5FYD8WFNFH',
  );
}
