// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcqwZ3Q4LipJoH20LuaIr5lE9ohnNt2yE',
    appId: '1:81873226425:web:b2e16480d09db81c87e968',
    messagingSenderId: '81873226425',
    projectId: 'lab-10-d4fdf',
    authDomain: 'lab-10-d4fdf.firebaseapp.com',
    storageBucket: 'lab-10-d4fdf.firebasestorage.app',
    measurementId: 'G-SDQWXJZWC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwqnhJ9kd2IbcNPG4YdmfkE5J24vmGI2g',
    appId: '1:81873226425:android:a122ac651a12a64e87e968',
    messagingSenderId: '81873226425',
    projectId: 'lab-10-d4fdf',
    storageBucket: 'lab-10-d4fdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWi9iFEWbjbZHSMwnRio4BT2X0EjNVwV0',
    appId: '1:81873226425:ios:2dbc38ec02f58db287e968',
    messagingSenderId: '81873226425',
    projectId: 'lab-10-d4fdf',
    storageBucket: 'lab-10-d4fdf.firebasestorage.app',
    iosBundleId: 'com.example.lab10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWi9iFEWbjbZHSMwnRio4BT2X0EjNVwV0',
    appId: '1:81873226425:ios:2dbc38ec02f58db287e968',
    messagingSenderId: '81873226425',
    projectId: 'lab-10-d4fdf',
    storageBucket: 'lab-10-d4fdf.firebasestorage.app',
    iosBundleId: 'com.example.lab10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcqwZ3Q4LipJoH20LuaIr5lE9ohnNt2yE',
    appId: '1:81873226425:web:f6b50c6b8b60fc7287e968',
    messagingSenderId: '81873226425',
    projectId: 'lab-10-d4fdf',
    authDomain: 'lab-10-d4fdf.firebaseapp.com',
    storageBucket: 'lab-10-d4fdf.firebasestorage.app',
    measurementId: 'G-NRLBKMXEEY',
  );

}