// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTsiC0ytJi_lB2cMM7NXqwgF0QUh0Ak7c',
    appId: '1:88891300553:web:db1edc8c4dbca8d9dfcb18',
    messagingSenderId: '88891300553',
    projectId: 'lab11-da72e',
    authDomain: 'lab11-da72e.firebaseapp.com',
    storageBucket: 'lab11-da72e.firebasestorage.app',
    measurementId: 'G-275EYGP3Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARVK0OYyl8PDY7Nq5_xVZHLpiylhtlczI',
    appId: '1:88891300553:android:c49a5d8cf1e59b56dfcb18',
    messagingSenderId: '88891300553',
    projectId: 'lab11-da72e',
    storageBucket: 'lab11-da72e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoOxBaDoN1hv0Hh3u3sUNI1IAqWvwhl68',
    appId: '1:88891300553:ios:0bc967a14e417672dfcb18',
    messagingSenderId: '88891300553',
    projectId: 'lab11-da72e',
    storageBucket: 'lab11-da72e.firebasestorage.app',
    iosBundleId: 'com.example.lab11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoOxBaDoN1hv0Hh3u3sUNI1IAqWvwhl68',
    appId: '1:88891300553:ios:0bc967a14e417672dfcb18',
    messagingSenderId: '88891300553',
    projectId: 'lab11-da72e',
    storageBucket: 'lab11-da72e.firebasestorage.app',
    iosBundleId: 'com.example.lab11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTsiC0ytJi_lB2cMM7NXqwgF0QUh0Ak7c',
    appId: '1:88891300553:web:4bc8d57fcd9f2998dfcb18',
    messagingSenderId: '88891300553',
    projectId: 'lab11-da72e',
    authDomain: 'lab11-da72e.firebaseapp.com',
    storageBucket: 'lab11-da72e.firebasestorage.app',
    measurementId: 'G-W3L93QB302',
  );
}
